= Day Trader

The heritage Stock trading application based on J2EE.

== Pre-requisites

* https://try.openshift.com[OpenShift 4 Cluster]
* https://strimzi.io[Strimzi Kafka]

== Prepare Cluster

Ensure the following operator is installed in cluster:

- https://operatorhub.io/operator/strimzi-kafka-operator[Strimzi Kafka]

[NOTE]: In OpenShift the operators can be installed via Operator Hub integration from Adminstrator console.

== Clone the sources

[source,bash]
----
git clone -b sko-demo https://github.com/kameshsampath/sample.daytrader8
----

We will refer to the cloned project sources folder as `$PROJECT_HOME`.

[source,bash]
----
cd $PROJECT_HOME
----

== Deploy Databases

On clusters where heritage application `sampledaytrader` is deployed, deployed MySQL:

[source,shell script]
----
oc apply -k k8s/db/mysql/prod

----

(Optional)

If you need Web based DB Console then run the following command on the clusters:

[source,shell script]
----
oc apply -k k8s/db/adminer/prod

----

== Deploy Kafka

[source,shell script]
----
oc apply -k k8s/kafka/prod

----

== Deploy Debezium KafkaConnect and MySQL KafkaConnector

[source,shell script]
----
oc apply -k k8s/debezium/prod

----

*NOTE*: This will take few mins for the Connector to be activated

Wait for the KafkaConnect `daytrader-debezium-connect` pod to be running:

[source,shell script]
----
watch oc get pods -l=strimzi.io/name=daytrader-debezium-connect

----

A successful KafkaConnect should show "Ready" to be "True":

[source,shell script]
----
 oc get KafkaConnect daytrader-debezium -ojsonpath='{.status.conditions[?(@.type=="Ready")].status}'

----

*NOTE*: It will take few seconds for the KafkaConnector to be reconciled. Wait for few mins before you run the following commands to check the status.

Check the status of the `mysql-daytrader-connector` to be ready:

[source,shell script]
----
 oc get KafkaConnector mysql-daytrader-connector -ojsonpath='{.status.conditions[?(@.type=="Ready")].status}'

----

== Deploy Application

[source,shell script]
----
oc apply -k k8s/sampledaytrader8/prod

----

[source,shell script]
----
export DAYTRADER_ROUTE="https://$(oc get route daytrader -ojsonpath='{.spec.host}')"
----

== Create and Populate the DB tables

[source,shell script]
----
curl -X GET "$DAYTRADER_ROUTE/io.openliberty.sample.daytrader8/config?action=buildDBTables"
----

[source,shell script]
----
oc scale --replicas=0 deploy/sampledaytrader8
oc scale --replicas=1 deploy/sampledaytrader8
----

[source,shell script]
----
curl -X GET "$DAYTRADER_ROUTE/io.openliberty.sample.daytrader8/config?action=buildDB"
----

== Create Debezium Connectors

[source,shell script]
----
oc apply -k k8s/debezium
----

== List Kafka Topics

[source,shell script]
----
./scripts/kafka-list-topics 
----

Will list the following topics, you should see one topic per table of the DB with prefix `openshift.inventory.`.

[source,text]
----
__consumer_offsets
connect-cluster-configs
connect-cluster-offsets
connect-cluster-status
openshift
openshift.traderdb.accountejb
openshift.traderdb.accountprofileejb
openshift.traderdb.holdingejb
openshift.traderdb.keygenejb
openshift.traderdb.orderejb
openshift.traderdb.quoteejb
schema-changes.traderdb
----

== Access the Application

[source,shell script]
----
$DAYTRADER_ROUTE/io.openliberty.sample.daytrader8/
----

== Development

=== Building Debezium MySql Connector

[source,shell script]
----
cd k8s/debezium
docker build --no-cache <container-registry>/debezium-connect
docker push <container-registry>/debezium-connect
----

*NOTE*: Be sure to update the k8s/debezium/debezium-connect.yaml with image image from the build

=== Image Streams

[source,shell script]
----
oc create -f https://raw.githubusercontent.com/OpenLiberty/open-liberty-s2i/master/imagestreams/openliberty-ubi-min.json
----

=== Deploy Application

[source,shell script]
----
oc new-app openliberty:~https://github.com/kameshsampath/sample.daytrader8#sko-demo -n daytrader-dev
----

[source,shell script]
----
oc create route edge --service=sampledaytrader8 --port=9080 daytrader
export DAYTRADER_ROUTE="https://$(oc get route daytrader -ojsonpath='{.spec.host}')"
----