CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED BY 'debezium';

CREATE USER IF NOT EXISTS 'replicator'@'%' IDENTIFIED BY 'replpass';

GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator'@'%';

CREATE USER IF NOT EXISTS 'debezium'@'%' IDENTIFIED BY 'debezium';

GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium'@'%';

CREATE DATABASE IF NOT EXISTS inventory;
CREATE DATABASE IF NOT EXISTS traderdb;

GRANT ALL PRIVILEGES ON inventory.* TO 'debezium'@'%';

GRANT ALL PRIVILEGES ON traderdb.* TO 'debezium'@'%';
